# ===== Site settings =====
title: Majinhai · Blog
description: 记录 · 研究 · 折腾
# 个人主页仓库必须留空；如果是项目页就写 "/仓库名"
baseurl: ""
# 你的站点域名（一定要带 https://）
url: "https://majinhai041214.github.io"

# ===== User settings (Particle 主题用到) =====
username: 马锦海的博客
user_title: Researcher & Developer
user_description: >
  计算机视觉 / 生成模型 / 工程实践。这里记录我的研究笔记、代码片段与想法。
email: your_email@example.com          # ← 换成你的邮箱
twitter_username:
github_username: majinhai041214
gplus_username:

# ===== Analytics（可选）=====
google-analytics:
  id: ""                                # 有 GA 再填，如 G-XXXX

# ===== Jekyll 基本项 =====
timezone: Asia/Shanghai
lang: zh-CN

# 这些目录不参与构建
exclude: ['package.json', 'src', 'node_modules']

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

